# config/meta.yml

meta_product_name: "Parallel"
meta_title: "Parallel - Une autre approche de la médecine"
meta_description: "Parallel vous offre un accès simplifié aux médecines alternatives
pour vous accompagner dans la découverte d'une nouvelle pratique de soin."
meta_image: "cover.png" # should exist in `app/assets/images/`
